### ISSUE TITLE
Missing domain dependency in npm package?

### ISSUE THREAD

**Issue by andrewlow** [mbrevoort/node-reggie#44]
For some reason the domain package ( https://www.npmjs.org/package/domain  ) appears to be non-specified requirement for the restify module that is embedded in reggie.

```
npm install reggie
./node_modules/.bin/reggie-server

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'domain'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/alow/npm/reggie/node_modules/reggie/node_modules/restify/lib/server.js:3:14)
```

**Comment by andrewlow** [comment]
Sigh.. sorry - accidentally got burned by $PATH and a really stale version of Node.js. 0.6.12 doesn't like this package (of course).
