### ISSUE TITLE
reggie-server do not start - TypeError: The super constructor to "inherits" must not be null or undefined

### ISSUE THREAD

**Issue by drusso85** [mbrevoort/node-reggie#56]
Command reggie-server -d ~/.reggie fails with error.
**node version**:v7.7.1 v8.1.1
**OS**: ubuntu 16.10
**Complete stacktrace**:
```
util.js:955
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:955:11)
    at Object.<anonymous> (/home/drusso/.nvm/versions/node/v8.1.1/lib/node_modules/reggie/node_modules/spdy/lib/spdy/server.js:460:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/drusso/.nvm/versions/node/v8.1.1/lib/node_modules/reggie/node_modules/spdy/lib/spdy.js:31:15)
```

**Comment by outer1** [comment]
i met the the problem in CentOS 6.5, could someone help?

**Comment by victor737-max** [comment]
same on Ubuntu 16.04

**Comment by renatoathaydes** [comment]
Can confirm, same on Ubuntu 16.04 LTS.

```
reggie-server -d ~/.reggie
util.js:948
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function
    at Object.inherits (util.js:948:11)
    at Object.<anonymous> (/usr/lib/node_modules/reggie/node_modules/spdy/lib/spdy/server.js:460:6)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/reggie/node_modules/spdy/lib/spdy.js:31:15)
```

**Comment by lealhugui** [comment]
Same on windows and on fedora.

**Comment by lealhugui** [comment]
From what I've seen, is an error on a dependency of reggie (restify). Since restify is only used for building endpoints, will commit a PR for changing it to express.
