### ISSUE TITLE
reggie fails to install

### ISSUE THREAD

**Issue by bahmutov** [mbrevoort/node-reggie#6]
npm i -g reggie

generates on Windows (node 0.10.6, npm 1.2.18)

```
npm http 404 https://registry.npmjs.org/npm/1.1.61
npm ERR! Error: version not found: 1.1.61 : npm/1.1.61
npm ERR!     at RegClient.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:269:14)
npm ERR!     at Request.self.callback (c:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:142:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:856:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (c:\Program Files\nodejs\node_modules\npm\node_modules\request\index.js:808:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:910:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
```

**Comment by bajtos** [comment]
@bahmutov Can you reproduce the problem with the latest (0.1.x) version of Reggie? We are depending on npm ~1.1.71 now.
